#!/bin/sh
DS_VERSION=${DS_VERSION:-"3.9"}
VCS_REF=$(git describe --tags --dirty --always)
BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S)
docker build --build-arg=DS_VERSION=$DS_VERSION --build-arg=VCS_REF=$VCS_REF --build-arg=BUILD_DATE=$BUILD_DATE
